name: Publish Nuget Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      id-token: write
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack --configuration Release --no-build -o ./nupkg  
      
      - name: Publish to Github Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "https://nuget.pkg.github.com/moo-ahmad/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}